add_newline = false
scan_timeout = 30

[character]                            # The name of the module we are configuring is "character"
error_symbol = "[âœ–](bold red) "

[cmd_duration]
min_time = 20_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[line_break]
disabled = true

[directory]
truncation_length = 8

[python]
disabled = true
detect_extensions = []
python_binary = ["./venv/bin/python", "python", "python3", "python2"]

[vagrant]
disabled = true

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[perl]
disabled = true
